services:
  onc-sml-sandbox:
    image: onc.sml.fhir:latest
    mem_reservation: 4048m
    container_name: onc.sml.fhir
    environment:
      - JAVA_OPTS="-Xmx6048m -DLOGGING_LEVEL_ROOT=TRACE -DLOGGING_LEVEL_MDMI=TRACE"
      - SPRING_CONFIG_LOCATION=file:/config/
      - SPRING_PROFILES_ACTIVE=ri
      - hapi.fhir.fhir-version=R4
      - hapi.fhir.fhir_version=R4
      - spring.main.allow-circular-references=TRUE
      #- ca.uhn.fhir.to.TesterConfig_SYSPROP_FORCE_SERVERS=
    volumes:
      - /data/splitlearn-docker/code_from_sean/oncml-phase2/FHIRDataDocker/config:/config
# DT - KEEP FOR LOADING DATA INTO FHIR SERVICE
      - /data/splitlearn-docker/onc_code/hapifhir-cli:/hapifhir-cli
      - /data/splitlearn-docker/cumulus/export_folder/run_etl_onc_condonly_2024_0604_161819/:/ndjson
      - /data/splitlearn-docker/docker_fhir_lucene:/target/lucenefiles:rw
#   - cumulus/export_folder/ObsRuns/run_etl_all_onc_enc_obsonly_2024_0515_135955/:/ndjson
#   - export_folder/ObsRuns/run_etl_all_onc_obsonly_2024_0513_231746/:/ndjson
#    network_mode: default
    networks:
      - splitlearn-transform
#    ports:
#      - "127.0.0.1:8181:8080"
    restart: always    
  org.onc.ml.transformation :
    image: onc.sml.transformation:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8282/mdmi/transformation" ]
      interval: 10s
      timeout: 2s
      retries: 30
      start_period: 10s    
    mem_reservation: 4048m
    container_name: onc.sml.transformation
    environment:
      - JAVA_OPTS="-Xmx6048m -DLOGGING_LEVEL_ROOT=TRACE -DLOGGING_LEVEL_MDMI=TRACE"
      - mdmi.sourceFilterFlag=true
#    network_mode: default
    networks:
      - splitlearn-transform
#    ports:
#      - "8282:8282"
    restart: always

networks:
    splitlearn-transform:
        name: splitlearn-transform
