
networks:
  public-net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/16
          ip_range: 172.200.1.0/24
    driver_opts:
      com.docker.network.bridge.name: central_public

services:
  central:
    build:
      context: .
      target: central
    privileged: true
    hostname: central
    container_name: central
    restart: on-failure
    environment:
#      - TZ=Asia/Kolkatha
      - WORLD_SIZE=3
      - CENTRAL_ADDRESS=172.200.1.1 
      - CENTRAL_PORT=7732
      - IFNAME=eth0
      - CONFIG=os
      - TZ=America/Indianapolis
      - MODEL_PATH=saves
    volumes:
      - ./tcpdump-logs/central:/tcpdump-logs
      - ./stunnel-logs/central:/var/log/stunnel
      - ./certs/ca_all.pem:/etc/stunnel/certs/ca.pem
      - ./certs/central.pem:/etc/stunnel/certs/central.pem
      - ./certs/central.key:/etc/stunnel/certs/central.key
      - ./saves/:/saves
    ports:
      - 5000:5000
    networks:
      public-net:
        ipv4_address: 172.200.1.1
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [ gpu ]

