
networks:
  public-net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/16
          ip_range: 172.200.1.0/24
    driver_opts:
      com.docker.network.bridge.name: central_public

services:
  hie2:
    build:
      context: .
      target: hie
    privileged: true
    container_name: hie2
    hostname: hie2
    environment:
#      - TZ=Asia/Kolkatha
      - TZ=America/Indianapolis
      - WORLD_SIZE=3
      - EPOCHS=10
      - ITERATIONS=1
      - RANK=2
      - IFNAME=eth0
      - CONFIG=os

      - CENTRAL_ADDRESS=172.200.1.3 #central
      - CENTRAL_PORT=3120
    volumes:
      - ./tcpdump-logs/hie2:/tcpdump-logs
      - ./stunnel-logs/hie2:/var/log/stunnel
      - ./certs/hie2.pem:/etc/stunnel/certs/client.pem
      - ./certs/hie2.key:/etc/stunnel/certs/client.key
      - ./certs/ca_central.crt:/etc/stunnel/certs/ca.pem

    networks:
      public-net:
        ipv4_address: 172.200.1.3
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [ gpu ]

