apiVersion: batch/v1
kind: Job
metadata:
  generateName: central-
  namespace: default
spec:
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      labels:
        split-learn-role: central
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: p3.2xlarge
        karpenter.sh/capacity-type: 'on-demand'
      containers:
        - name: central
          imagePullPolicy: Always
          image: 745222113226.dkr.ecr.us-east-1.amazonaws.com/bookzurman/central:latest
          command:  ["/usr/local/bin/supervisord"]  # ["tail", "-f",  "/dev/null"] #
          ports:
            - containerPort: 3130
              protocol: TCP
          env:
            - name: CENTRAL_ADDRESS
              value: 127.0.0.1
            - name: CENTRAL_PORT
              value: "7732"
            - name: WORLD_SIZE
              value: "2"
            - name: IFNAME 
              value: eth0
            - name: CONFIG
              value: os
            - name: MODEL_PATH
              value: "s3://bookzurma-meld-prod/splitlearn"
            - name: CUDA_LAUNCH_BLOCKING
              value: "1"
          volumeMounts:
            - name: central-vol
              mountPath: /etc/stunnel/stunnel.conf
              subPath: stunnel.conf
            - name: central-vol
              mountPath: /etc/stunnel/certs/ca.pem
              subPath: ca.pem
            - name: central-vol
              mountPath: /etc/stunnel/certs/central.pem
              subPath: central.pem
            - name: central-vol
              mountPath: /etc/stunnel/certs/central.key
              subPath: central.key
            - name: fromhost
              mountPath: /var/log/stunnel
            - name: site-packages
              mountPath: /usr/local/lib64/python3.11/site-packages
          resources:
            limits:
              nvidia.com/gpu: "1"
      volumes:
        - name: central-vol
          configMap:
            name: central
        - name: fromhost
          hostPath:
            path: /tmp
            type: Directory
        - name: site-packages
          persistentVolumeClaim:          
            claimName: site-packages 
      tolerations:
        - key: "nvidia.com/gpu"
          value: "present"
          operator: "Equal"
          effect: "NoSchedule"
      restartPolicy: OnFailure
# ---
# # hie1
# apiVersion: batch/v1
# kind: Job
# metadata:
#   generateName: hie1-
#   namespace: default
# spec:
#   template:
#     spec:
#       # hostNetwork: true
#       containers:
#         - name: hie1   
#           imagePullPolicy: Always
#           image: 745222113226.dkr.ecr.us-east-1.amazonaws.com/bookzurman/hie1:latest
#           # command:  ["tail", "-f",  "/dev/null"]  #["sh", "-c", "/tmp/init.sh"]
#           env:
#             - name: CENTRAL_ADDRESS
#               value: localhost
#             - name: CENTRAL_PORT
#               value: "3120"
#             - name: WORLD_SIZE
#               value: "2"
#             - name: RANK
#               value: "1"
#             - name: IFNAME 
#               value: eth0
#             - name: CONFIG
#               value: os
#             - name: CENTRAL_STUNNEL_ADDRESS
#               value: bzm-splitlearn.interop.community:65443
#             - name: DATA_PATH
#               value: /usr/local/lib64/python3.11/site-packages/bzdata
#           volumeMounts:
#             - name: hie-vol
#               mountPath: /etc/stunnel/certs/client.pem
#               subPath: client.pem            
#             - name: hie-vol
#               mountPath: /etc/stunnel/certs/client.key
#               subPath: client.key            
#             - name: hie-vol
#               mountPath: /etc/stunnel/certs/ca.pem
#               subPath: ca.pem    
#             - name: fromhost
#               mountPath: /var/log/stunnel  
#             - name: site-packages
#               mountPath: /usr/local/lib64/python3.11/site-packages
#       volumes:
#         - name: hie-vol
#           configMap:
#             name: hie1
#         - name: fromhost
#           hostPath:
#             path: /tmp
#             type: Directory
#         - name: site-packages
#           persistentVolumeClaim:          
#             claimName: site-packages 
#       tolerations:
#         - key: "dedicated"
#           value: "ml"
#           operator: "Equal"
#           effect: "NoSchedule"
#       affinity:
#           nodeAffinity:
#             requiredDuringSchedulingIgnoredDuringExecution:
#               nodeSelectorTerms:
#                 - matchExpressions:
#                     - key: kubernetes.io/os
#                       operator: NotIn
#                       values:
#                         - windows
#                     - key: ComputeSource
#                       operator: In
#                       values:
#                         - "managed_node_groups"
#       restartPolicy: OnFailure


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: central
#   namespace: default
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: bzm-splitlearn.interop.community,hie1-splitlearn.interop.community
#     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#     service.beta.kubernetes.io/aws-load-balancer-target-node-labels: ComputeSource=managed_node_groups
#     service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: load_balancing.cross_zone.enabled=true
# spec:
#   selector:
#     split-learn-role: central
#   ports:
#   - name: https
#     nodePort: 31076
#     port: 443
#     protocol: TCP
#     targetPort: 443
#   - name: http
#     nodePort: 32737
#     port: 80
#     protocol: TCP
#     targetPort: 80
#   - name: stunnel
#     nodePort: 30538
#     port: 65443
#     protocol: TCP
#     targetPort: 3130
#   loadBalancerClass: service.k8s.aws/nlb
#   type: LoadBalancer

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: site-packages
# spec:
#   accessModes:
#     - ReadWriteOnce 
#   resources:
#     requests:
#       storage: 12Gi
#   storageClassName: io1
#   volumeName: pvc-10ed83a5-e24b-4444-a253-a6deca1e06ce

