version: '3.7'

services:

  fhir:
    container_name: fhir
    image: "onc.sml.fhir:latest"
    ports:
      - "8080:8080"
      - "9010:9010"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    ports:
     - "5432:5432"  
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data


  org.onc.ml.transformation :
    image: onc.sml.transformation:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8282/mdmi/transformation" ]
      interval: 60s
      timeout: 2s
      retries: 30
      start_period: 60s    
    mem_reservation: 4048m
    container_name: onc-mdmi
    environment:
      - JAVA_OPTS="-Xmx6048m"
      - LOGGING_LEVEL_MDMI=INFO
      - MDMI_SOURCE_FILTER_FLAG=true
    network_mode: default
    ports:
      - "8282:8282"
    restart: always




  # synthea:
    # container_name: synthea
    # image:  onc.sml.synthea 
    # volumes:
      # - ./synthea/fhir:/oncfhirinput
    # depends_on:
      # - org.onc.ml.transformation      

  # finishera:
  #   container_name: wait-for-synthea
  #   image: alpine
  #   healthcheck:
  #     test: exit 0
  #     interval: 2s
  #   depends_on:
  #     synthea:
  #       condition: service_completed_successfully

  # generate:
  #   container_name: generate
  #   image: alpine

  # finisherb:
  #   container_name: wait-for-generate
  #   image: alpine
  #   healthcheck:
  #     test: exit 0
  #     interval: 2s
  #   depends_on:
  #     generate:
  #       condition: service_completed_successfully        